# Generated by Django 4.2.1 on 2023-05-22 17:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(help_text='Full name/alias/nickname as you would usually sign your emails, e.g. John Johnson or Lord Demogorgon.', max_length=255)),
                ('email', models.EmailField(help_text='The email address of the main label. It will be needed for logging in.', max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to=users.models.user_directory_path, verbose_name='avatar')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
