# Generated by Django 4.2.1 on 2023-07-12 08:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path, verbose_name='avatar'),
        ),
    ]
