# Generated by Django 4.2.1 on 2023-05-22 17:09

import ImageLib.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('Date_of_Birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер главы')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('release_year', models.DateField(verbose_name='Год выпуска')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('Date_of_Birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Формат выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='ImageLib.manga', verbose_name='Произведение')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер страницы')),
                ('image', models.ImageField(upload_to=ImageLib.models.Chapter_directory_path, verbose_name='Страница')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.chapter', verbose_name='Глава')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='painter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.painter', verbose_name='Художник'),
        ),
        migrations.AddField(
            model_name='manga',
            name='release_format',
            field=models.ManyToManyField(to='ImageLib.releaseformat', verbose_name='Формат выпуска'),
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.volume', verbose_name='Том'),
        ),
    ]
