# Generated by Django 4.2.1 on 2023-06-22 13:07

import ImageLib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='painter',
            options={'verbose_name': 'Художник', 'verbose_name_plural': 'Художники'},
        ),
        migrations.AlterModelOptions(
            name='releaseformat',
            options={'verbose_name': 'Формат выпуска', 'verbose_name_plural': 'Форматы выпуска'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Том', 'verbose_name_plural': 'Тома'},
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_cover',
            field=models.ImageField(default=None, upload_to=ImageLib.models.manga_cover_directory_path, verbose_name='Обложка манги'),
            preserve_default=False,
        ),
    ]
