# Generated by Django 4.2.1 on 2023-07-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0004_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageLib.manga', verbose_name='Произведение'),
        ),
    ]
