# Generated by Django 4.2.1 on 2023-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0006_genre_manga_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('finished', 'завершен'), ('continue', 'продолжается')], max_length=100, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
