# Generated by Django 4.2.1 on 2023-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0007_alter_manga_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='ImageLib.genre', verbose_name='Жанры'),
        ),
    ]
