# Generated by Django 4.2.1 on 2023-09-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0008_alter_manga_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageLib.volume', verbose_name='Том'),
        ),
    ]
