# Generated by Django 4.2.1 on 2023-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLib', '0009_alter_chapter_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, to='ImageLib.genre', verbose_name='Жанры'),
        ),
    ]
